apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: backstage-learning
  title: Backstage Learning Service
  description: Main backend service for Backstage learning project

  annotations:
    github.com/project-slug: amirSohel007/backstage-learning

  tags:
    - nodejs
    - backstage
    - mongodb
    - learning

  links:
    - url: https://github.com/amirSohel007/backstage-learning
      title: GitHub Repository

spec:
  type: service
  lifecycle: production
  owner: user:guest

  providesApis:
    - backstage-learning-api

---
apiVersion: backstage.io/v1alpha1
kind: API

metadata:
  name: backstage-learning-api
  description: Public APIs for Backstage learning project

spec:
  type: openapi
  lifecycle: production
  owner: user:guest

  definition: |
    openapi: 3.0.0

    info:
      title: Backstage Learning API
      version: 1.0.0

    paths:
      /activities:
        get:
          summary: Get Activities

      /orders:
        get:
          summary: Get Orders
