apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: backstage-learning
  title: Backstage Learning Service
  description: Main backend service for Backstage learning project

  annotations:
    github.com/project-slug: amirSohel007/backstage-learning

  tags:
    - backstage
    - learning
    - nodejs

  links:
    - url: https://github.com/amirSohel007/backstage-learning
      title: GitHub Repository

spec:
  type: service
  lifecycle: production
  owner: user:guest
